
apiVersion: apps/v1
kind: Deployment
metadata:  
  namespace: webapp
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        namespace: webapp
    spec:
      containers:
        - name: webapp
          image: 692859929342.dkr.ecr.us-east-1.amazonaws.com/common/webapp:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 2