apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: webapp
  name: webapp-hpa
  labels:
    app: webapp    
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15
