# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
# spec:
#   type: NodePort
#   selector:
#     app: webapp
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30320
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 5678
#   selector:
#     app: hello