
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  namespace: {{ .Values.namespace }}
  name: {{ .Values.app }}-deployment
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        namespace: {{ .Values.namespace }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 2