---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: webapp-svc
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
