name: full-cicd-wenbapp
on:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: 7sergaza7/task2bcloud/.github/workflows/_webapp.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 
  call-deploy:
    uses: 7sergaza7/task2bcloud/.github/workflows/_eks.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  # call-deploy:
  #   uses: 7sergaza7/task2bcloud/.github/workflows/_k8s.yml
