name: full-cicd-wenbapp
on:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/_webapp.yml@main
  call-deploy:
    uses: ./.github/workflows/_eks.yml@main
  call-deploy:
    uses: ./.github/workflows/_k8s.yml@main
