name: full-cicd-wenbapp
on:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: 7sergaza7/task2bcloud/.github/workflows/_webapp.yml
  call-deploy:
    uses: 7sergaza7/task2bcloud/.github/workflows/_eks.yml
  # call-deploy:
  #   uses: 7sergaza7/task2bcloud/.github/workflows/_k8s.yml
