name: full-cicd-wenbapp
on:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/templates/_webapp.yml@main
  call-deploy:
    uses: ./.github/templates/_eks.yml@main
  call-deploy:
    uses: ./.github/templates/_k8s.yml@main
