name: full-cicd-wenbapp
on:
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/_webapp.yml
  call-deploy:
    uses: ./.github/workflows/_eks.yml
  call-deploy:
    uses: ./.github/workflows/_k8s.yml
